### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by RakibRyan** [algernon-A/LSM-Revisited#6]
Hi I was wondering if you would add a license like MIT or GNU to it. I'd like to publish to nexus mods for people like me who own the game on epic games.

**Comment by algernon-A** [comment]
The mod is already available for free for Epic Games users via the Discord, and given my past experiences with Nexus Mods I won't ever do anything to support use of that platform ever again.

As for licensing, no, the mod inlcudes encumbered code that I have permission to distribute in binary form via the Steam Workshop and Discord, but which cannot be re-licenced.

**Comment by RakibRyan** [comment]
Thanks for making it available on discord. If you don't mind can I ask what
made your experience bad in nexus mods? For the most part it seems fine to
me.

**Comment by algernon-A** [comment]
Sorry for the delay in responding, I've been trying to think of wording that doesn't end in a rant.

I failed, so I'll just leave it at "they have zero respect for mod creators".
